name: AI_PREDICITONS

on:
  push:
    branches:
      - development
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: vo_ai_predictions

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/v') 
        run: echo "${{ github.ref_name }}"
      - name: test tag
        if: startsWith(github.ref, 'refs/tags/v')        
        run: echo "${{ github.ref_name }}"
      - name: getTest
        if: github.ref == 'refs/heads/development'
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: dev echo
        if: github.ref == 'refs/heads/development'
        run: echo "${{ steps.getTest.outputs.version }}"

      # - name: Push
      #   if: github.ref == 'refs/heads/development'
      #   run: echo "This is a dev test"
      #   run: echo "Build and push"
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     build-args: |
      #       version=${{ steps.tag.outputs.tag }}
      #     tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
