name: AI_PREDICITONS

on:
  push:
    branches:
      - development
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: vo_ai_predictions

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "${{ secrets.ACR_ENDPOINT }}"
        if: github.ref == 'refs/heads/development'
        run: echo "This is a dev test"
      - name: Build & Push
        run: echo "Build and push"
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     build-args: |
      #       version=${{ steps.tag.outputs.tag }}
      #     tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
